<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <script>
        //因为标准并没有指定如何构造一个Promise对象，所以我们同样以目前一般Promise实现中通用的方法来构造一个Promise对象，也是ES6原生Promise里所使用的方式：
        //Promise构造函数接受一个executor函数，executor函数执行完同步或异步操作后，调用它的两个参数resolve和reject
        var promise = new Promise(function(resolve,reject){
            /*
            * 如果操作成功，调用resolve并传入value，
            * 如果操作失败，调用reject并传入reason*/
        });
        //我们先实现构造函数的框架如下：
        function Promise(executor) {
            console.log(this)
            var self = this;
            self.status = 'pending'; // Promise 当前的状态
            self.data = undefined; // Promise的值
            self.onResolvedCallback = []; //Promise resolve时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
            self.onRejectedCallback = []; //Promise reject时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面

            function resolve(value) {
                //todo
                if(self.status === 'pending') {
                    self.status = 'resolved';
                    self.data = value;
                    for(var i=0; i<self.onResolvedCallback.length; i++) {
                        self.onResolvedCallback[i](value);
                    }
                }
            }
            function reject(reason) {
                //todo
                if(self.status === 'pending') {
                    self.status = 'rejected';
                    self.data = reason;
                    for(var i=0; i<self.onRejectedCallback.length; i++) {
                        self.onRejectedCallback[i](reason);
                    }
                }
            }
            /*
            * 基本上就是在判断状态为pending之后把状态改为相应的值，
            * 并把对应的value和reason存在self的data属性上面，之后执行相应的回调函数*/

            try { //考虑到执行executor的过程中可能出错，所以我们用try/catch块给包起来，并且在出错后以catch到的值reject掉这个Promise
                executor(resolve,reject); //执行executor并传入相应的参数
            } catch(e) {
                reject(e)
            }
        }
        //下面实现then的方法
        //then方法接收两个参数，onResolved，onRejected,分别为Promise成功或失败后的回调
        Promise.prototype.then = function(onResolved,onRejected) {
            var self = this;
            var promise2;
            //根据标准，如果then的参数不是function，则我们需要忽略他，此处以如下方式处理
            onResolved = typeof onResolved === 'function' ? onResolved : function(v) {};
            onRejected = typeof onRejected === 'function' ? onRejected : function(r) {};

            if(self.status === 'resolved') {
                //如果promise1(此处为this/self)的状态已经确定并且是resolved，我们调用onResolved
                //因为考虑到可能是throw，所以我们将其包在try/catch块里
                return promise2 = new Promise(function(resolve, reject) {
                    try {
                        var x = onResolved(self.data);
                        if(x instanceof Promise) {//如果onResolved的返回值是一个Promise对象，直接取它的结果做为Promise2的结果
                            x.then(resolve, reject);
                        }
                        resolve(x);  //否则，以它的返回值返回做为Promise2的结果
                    } catch (e) {
                        reject(e);   //如果出错，以捕获到的错误做为Promise2的结果
                    }
                })
            }

            //此处与前一个if块的逻辑几乎相同，区别在于所调用的是onRejected函数
            if(self.status === 'rejected') {
                return promise2 = new Promise(function(resolve, reject) {
                    try {
                        var x = onRejected(self.data);
                        if(x instanceof Promise) {
                            x.then(resolve, reject);
                        }
                    } catch (e) {
                        reject(e);
                    }
                })
            }

            if(self.status === 'pending') {
                //如果当前的Promise还处于pending状态，我们并不能确定调用onResolved还是onRejected;
                //只能等到Promise的状态确定后，才能确定如何处理
                //所以我们需要把我们的 两种情况 的处理逻辑做为callback放入promise1(此处即this/self)的回调数组里
                //逻辑本身跟第一个if块内的几乎一致
                return promise2 = new Promise(function(resolve, reject) {
                    self.onRejectedCallback.push(function(value) {
                        try {
                            var x = onResolved(self.data);
                            if(x instanceof Promise) {
                                x.then(resolve, reject);
                            }
                        } catch (e) {
                            reject(e);
                        }
                    });
                    self.onrejectedCallback.push(function(reason) {
                        try {
                            var x = onRejected(self.data);
                            if(x instanceof Promise) {
                                x.then(resolve, reject);
                            }
                        } catch (e) {
                            reject(e);
                        }
                    })
                })
            }
            //Promise有三个状态，分成三个if块来处理，里面分别都返回一个new Promise
        };
        //catch方法
        Promise.prototype.catch = function(onRejected) {
            return this.then(null,onRejected);
        }




        /*
       *上面的代码基本实现了Promise构造函数的主体，但目前还有两个问题：
       * 1.我们给executor函数传了两个参数：resolve和reject，这两个参数目前还没有定义
       * 2.executor有可能会出错(throw)，类似下面这样，如果executor出错，Promise应该被其throw出的值reject：*/
        new Promise(function(resolve,reject) {
            throw 2;
        })
        //所以我们需要在构造函数里定义resolve和reject这两个函数：

        /*
        * 根据标准我们知道如下，promise2的值取决于then里面函数返回值：*/
        promise2 = promise1.then(function(value) {
            return 2;
        }, function(reason) {
            throw new Error('something went wrong')
        }).catch((e) => {
            console.log(e);
        })




        /*
        * 以上的实现中并没有考虑隐藏this上的变量，这使得这个Promise的状态可以在executor函数外部被改变，
        * 在一个靠谱的实现里，构造出的Promise对象的状态和最终结果应当是无法从外部改变的。*/













    </script>
</body>
</html>